# ===========================================
# Site Settings
# ===========================================
# Header
site_title: DIOSTUDIO
site_description: 保持前进，以致更好！
# ---Optional ---
# site_avatar: /images/avatar.jpg
artical_license_statement:
# ---End Optional ---
menu:
  Home: /
  Archives: /archives
  Collect: /collect.html
  We: /we.html
# AboutMe: /about.html

# display widgets
widgets:
# - archives
# - search
#- social_links
- recent_posts
# - tagcloud

# widget behavior
archive_type: 'monthly'
show_count: true
# Content
excerpt_link: Read More
# favico 
favicon: /images/avatar.jpg

# ===========================================
# Miscellaneous Settings
# ===========================================
# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:
# Disqus
disqus:
  enable: true
  shortname:
  count: true
# changyan
changyan:
  enable: false
  appid:
  appkey:
# duoshuo
duoshuo:
  enable: false
  shortname:
# Visitors
leancloud_visitors:
  enable: true
  app_id:
  app_key:

# Search 
# Note: please install hexo-generator-search plugin and config the root _config.yml (not theme's _config.yml) as below value search.json(https://www.npmjs.com/package/hexo-generator-search):
#search:
#  path: search.json
#  field: post
